apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: derp-db-pvc-new2
  namespace: derp
spec:
  accessModes:
  - ReadWriteOnce
  #- ReadWriteMany
  resources:
    requests:
      storage: 1Gi
