apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: derp-web-ingress
  namespace: derp
spec:
  rules:
  - host: dragonbytes.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: derp-web-svc
            port:
              number: 80 # same as external ip set in service