apiVersion: v1
kind: Service
metadata:
  name: derp-web-svc
  namespace: derp
spec:
  selector:
    app: derp-web
  ports:
    - protocol: TCP
      port: 8080 # external port (doesn't have to be the same)
      targetPort: 8080