name: deployment pipeline
on:
- push
- workflow_dispatch
jobs:
  automated_testing:
    runs-on: self-hosted
    steps:
    - name: Check out the code. 
      uses: actions/checkout@v4

    # - name: Check if Dotnet format changed anything.
    #   run: |
    #     nix-shell -p dotnet-sdk_9 --run "
    #       dotnet format --verify-no-changes --verbosity diagnostic DerpRaven.Api
    #       dotnet format --verify-no-changes --verbosity diagnostic DerpRaven.Shared
    #       dotnet format --verify-no-changes --verbosity diagnostic DerpRaven.NTests
    #       dotnet format --verify-no-changes --verbosity diagnostic DerpRaven.Web
    #       dotnet build --warnaserror DerpRaven.Api
    #       dotnet build --warnaserror DerpRaven.Shared
    #       dotnet build --warnaserror DerpRaven.NTests
    #       dotnet build --warnaserror DerpRaven.Web
    #     "

    # - name: Run the tests.
    #   run: |
    #     docker build \
    #       -f ./Test.Api.Dockerfile \
    #       -t thomas_test_container \
    #       .

    #     docker run --rm thomas_test_container
    #     echo "going to deploy!!!"

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
          
    - name: build and push api to dockerhub
      run: |
        docker build \
          -f ./Api.Dockerfile \
          -t ${{ vars.DOCKERHUB_USERNAME }}/derp-raven-api:${{ github.run_number }} \
          .

        docker push -q ${{ vars.DOCKERHUB_USERNAME }}/derp-raven-api:${{ github.run_number }}

    - name: build and push web to dockerhub
      run: |
        docker build \
          -f ./Web.Dockerfile \
          -t ${{ vars.DOCKERHUB_USERNAME }}/derp-raven-web:${{ github.run_number }} \
          --build-arg base_address="https://derp-api-svc:8080" \
          .

        docker push -q ${{ vars.DOCKERHUB_USERNAME }}/derp-raven-web:${{ github.run_number }}

    - name: deploy web to kubernetes
      run: |
        kubectl apply -f kube/namespace.yml
        export BUILD_NUMBER=${{ github.run_number }}
        
        for FILE in "kube"/*
        do
          cat "$FILE" | envsubst | kubectl apply -f -
        done

    