name: deployment pipeline
on:
- push
- workflow_dispatch
jobs:
  automated_testing:
    runs-on: self-hosted
    steps:
    - name: Check out the code. 
      uses: actions/checkout@v4

    - name: Install .NET MAUI Workloads
      run: dotnet workload restore

    - name: Check if Dotnet format changed anything.
      run: |
        dotnet format --verify-no-changes --verbosity diagnostic

    - name: Check if there were any build errors.
      run: |
        dotnet build --warnaserror

    - name: Run the tests.
      run: |
        docker build \
          -f ./Test.Api.Dockerfile \
          -t thomas_test_container \
          .

        docker run --rm thomas_test_container
        echo "going to deploy!!!"

