name: deployment pipeline
on:
- push
- workflow_dispatch
jobs:
  automated_testing:
    runs-on: self-hosted
    steps:
    - name: Check out the code. 
      uses: actions/checkout@v4

    - name: Check if Dotnet format changed anything.
      run: |
        nix-shell -p dotnet-sdk_9 --run "bash -c '
          dotnet restore
          dotnet format --verify-no-changes --verbosity diagnostic
          dotnet build --warnaserror
        '"

    - name: Run the tests.
      run: |
        docker build \
          -f ./Test.Api.Dockerfile \
          -t thomas_test_container \
          .

        docker run --rm thomas_test_container
        echo "going to deploy!!!"

