name: deployment pipeline
on:
- push
- workflow_dispatch
jobs:
  automated_testing:
    runs-on: self-hosted
    steps:
    - name: check out code
      uses: actions/checkout@v4 # get the repo in the actions runner (running get clone)
  
    - name: check if dotne format changed anything
      run: |
        dotnet format --verify-no-changes --verbosity diagnostic

    - name: Build No Error
      run: |
        dotnet build --warnaserror

    - name: test the 
      run: |
        docker build \
          -f ./Test.Api.Dockerfile \
          -t thomas_test_container \
          .

        docker run --rm thomas_test_container
        echo "going to deploy!!!"

